# Builds and deploys the AI Expert system to the Bazar

name: Builds and deploys the AI Expert system to the Bazar
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Archive
      if: success()
      uses: vimtor/action-zip@v1
      with:
        files: ./dist/
        dest: ./${{ github.event.repository.name }}.zip

    - name: Publish
      if: success()
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: 'https://ainiro.io/magic/system/file-system/file'
        method: 'PUT'
        timeout: 50000
        customHeaders: '{
          "Content-Type": "multipart/form-data",
          "Authorization": "Bearer ${{ secrets.TOKEN }}"
          }'
        data: '{"folder": "/etc/bazar/frontends/"}'
        files: '{"file": "./${{ github.event.repository.name }}.zip"}'

    - name: Uploading description
      if: success()
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: 'https://ainiro.io/magic/system/file-system/file'
        method: 'PUT'
        timeout: 50000
        customHeaders: '{
          "Content-Type": "multipart/form-data",
          "Authorization": "Bearer ${{ secrets.TOKEN }}"
          }'
        data: '{"folder": "/etc/bazar/frontends/"}'
        files: '{"file": "./README.md"}'

    - name: Renaming description file
      if: success()
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: 'https://ainiro.io/magic/system/file-system/rename'
        method: 'POST'
        timeout: 50000
        customHeaders: '{
          "Content-Type": "application/json",
          "Authorization": "Bearer ${{ secrets.TOKEN }}"
          }'
        data: '{
          "oldName": "/etc/bazar/frontends/README.md",
          "newName": "${{ github.event.repository.name }}.md"
          }'